name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - CONTRIBUTING.md
      - renovate.json
      - ".github/workflows/**"
      - .releaserc.yml
      - .scalafix.conf
      - .scalafmt.conf
      - "package*.json"
      - codecov.yml
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
  release:
    name: Release on GitHub
    runs-on: ubuntu-22.04
    env:
      TERM: dumb
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup scala environment
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17
      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - name: Import GPG key for signing commits and release on Maven Central
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PGP_SECRET }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install
      - name: Publish on GitHub
        id: publish
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
      - name: Generate scaladoc
        run: sbt doc
      - name: Publish scaladoc on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/scala-3.3.0/api