name: Test

on:
  push:
    branches-ignore:
      - main
      - renovate/configure
    paths-ignore:
      - CHANGELOG.md
      - README.md
      - CONTRIBUTING.md
      - renovate.json
      - ".github/workflows/**"
      - .releaserc.yml
      - "package*.json"
  workflow_call:

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-20.04
    env:
      TERM: dumb
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup scala environment
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17
      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - name: Lint with scalafmt
        run: sbt scalafmtCheckAll
      - name: Check with scalafix
        run: sbt 'scalafixAll --check'
      - name: Test
        run: sbt clean coverage test coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: target/scala-3.3.0/scoverage-report
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
      - name: SonarCloud scan fixed
        uses: pervasive-cats/sonarcloud-scoverage-fix@v1.0.1
        with:
          scoverageReport: target/scala-3.3.0/scoverage-report/scoverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
